In [1]:
import matplotlib.pyplot as plt 
#Petit tuto pour apprendre à utiliser la base de donnée stats_pokemons.db 
#La lecture de la base de donnée se fait via des commandes en SQL et les deux bibliothèques suivantes :
import pandas as pd
import sqlite3 
conn = sqlite3.connect('stats_pokemons/stats_pokemons.db') #Outil permettant d'exploiter la base de données

In [ ]:
def dict_to_list(dict):
    #Transforme un dictionnaire en liste de listes    
    list = []
    for key, value in dict.items():
        list.append([key, value])
    return list

In [ ]:
data_file = 'usage/gen9ou-0.json'
df = pd.read_json(data_file)
df = df.transpose()
df = df.applymap(lambda cell: dict_to_list(cell) if isinstance(cell, dict) else cell)
df = df.loc[:, ['Moves', 'Abilities', 'usage']]

In [3]:
request = 'SELECT * FROM Pokemon '
df_fire_type_atk_spa_AVG = pd.read_sql(request, conn)
df_fire_type_atk_spa_AVG

,ID,Name,Form,Type1,Type2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Can Evolve
0,1,Bulbasaur,,Grass,Poison,318,45,49,49,65,65,45,1,1
1,2,Ivysaur,,Grass,Poison,405,60,62,63,80,80,60,1,1
2,3,Venusaur,,Grass,Poison,525,80,82,83,100,100,80,1,0
3,4,Charmander,,Fire,,309,39,52,43,60,50,65,1,1
4,5,Charmeleon,,Fire,,405,58,64,58,80,65,80,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,1006,Iron Valiant,,Fairy,Fighting,590,74,130,90,120,60,116,9,0
1190,1007,Koraidon,,Fighting,Dragon,670,100,135,115,85,100,135,9,0
1191,1008,Miraidon,,Electric,Dragon,670,100,85,100,135,115,135,9,0
1192,1009,Walking Wake,,Water,Dragon,590,99,83,91,125,83,109,9,0
1193,1010,Iron Leaves,,Grass,Psychic,590,90,130,88,70,108,104,9,0